version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: event_tracker_api
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    ports:
      - "9095:9095"
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Environment variables:' &&
        echo DB_USER=$${DB_USER} &&
        echo DB_HOST=$${DB_HOST} &&
        echo DB_PORT=$${DB_PORT} &&
        echo DB_NAME=$${DB_NAME} &&
        uvicorn app.main:app --host 0.0.0.0 --port 9095 --reload
      "