version: '3.8'

services:
  api:
    build: .
    ports:
      - "9095:9095"
    environment:
      - DATABASE_URL=postgresql://events_tracker_appuser:th1sP@ssw0rd1sB@d@88.161.169.84:25432/events_tracker_testsdb
    volumes:
      - ./:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 9095 --reload --reload-dir /code
